using Xunit;

namespace RynorArch.Generator.Tests;

public sealed class GeneratorOutputTests
{
    [Fact]
    public void Generates_repository_and_specification_outputs_without_compilation_errors()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;
            using Microsoft.EntityFrameworkCore;

            [assembly: Architecture(Pattern = ArchitecturePattern.Repository, UseSpecification = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; init; } = string.Empty;
            }
            """);

        Assert.Contains("Trip.Repository.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Specification.g.cs", result.GeneratedSources.Keys);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_stable_specification_output_snapshot()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(Pattern = ArchitecturePattern.Repository, UseSpecification = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; init; } = string.Empty;
            }
            """);

        var generatedSource = Normalize(result.GeneratedSources["Trip.Specification.g.cs"]);

        Assert.Contains("// <auto-generated/>", generatedSource);
        Assert.Contains("using System;", generatedSource);
        Assert.Contains("using System.Collections.Generic;", generatedSource);
        Assert.Contains("using System.Linq.Expressions;", generatedSource);
        Assert.Contains("using RynorArch.Abstractions.Interfaces;", generatedSource);
        Assert.Contains("using Demo.Domain;", generatedSource);
        Assert.Contains("namespace Demo.Domain.Specifications;", generatedSource);
        Assert.Contains("public sealed class TripSpecification : ISpecification<Trip>", generatedSource);
        Assert.Contains("public string? Destination { get; init; }", generatedSource);
        Assert.Contains("Expression<Func<Trip, bool>> filter = x => x.Destination.Contains(Destination!);", generatedSource);
        Assert.Contains("public IReadOnlyList<Expression<Func<Trip, object>>> Includes { get; init; } = Array.Empty<Expression<Func<Trip, object>>>();", generatedSource);
        Assert.Contains("return Expression.Lambda<Func<Trip, bool>>(combined, parameter);", generatedSource);
    }

    [Fact]
    public void Generates_fullstack_feature_set_for_aggregate_roots()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.FullStack,
                UseSpecification = true,
                UseUnitOfWork = true,
                EnableValidation = true,
                GenerateDtos = true,
                GenerateEfConfigurations = true,
                GenerateCachingDecorators = true,
                GeneratePagination = true)]

            namespace Demo.Domain;

            [Entity]
            [AggregateRoot]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; init; } = string.Empty;
            }
            """);

        Assert.Contains("Trip.Cqrs.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Repository.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Specification.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Validation.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripDto.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripConfiguration.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("GetTripByIdQueryCacheBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripPaginationExtensions.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.DomainEvents.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("IUnitOfWork.g.cs", result.GeneratedSources.Keys);
    }

    private static string Normalize(string value)
        => value.Replace("\r\n", "\n").Trim();
}
