using Xunit;

namespace RynorArch.Generator.Tests;

public sealed class GeneratorOutputTests
{
    [Fact]
    public void Generates_repository_and_specification_outputs_without_compilation_errors()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;
            using Microsoft.EntityFrameworkCore;

            [assembly: Architecture(Pattern = ArchitecturePattern.Repository, UseSpecification = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; init; } = string.Empty;
            }
            """);

        Assert.Contains("Trip.Repository.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Specification.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.CrudInfrastructure.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.GenerationReport.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("public interface ITripRepository : ICrudRepository<Trip>;", result.GeneratedSources["Trip.Repository.g.cs"]);
        Assert.Contains("public sealed partial class TripRepository : CrudRepository<Trip>, ITripRepository", result.GeneratedSources["Trip.Repository.g.cs"]);
        Assert.Contains("private static class EntityTraits<TEntity> where TEntity : class", result.GeneratedSources["RynorArch.CrudInfrastructure.g.cs"]);
        Assert.Contains("// rynor-artifact: Global.GenerationReport", result.GeneratedSources["RynorArch.GenerationReport.g.cs"]);
        Assert.Contains("ApplySpecificationForList", result.GeneratedSources["RynorArch.CrudInfrastructure.g.cs"]);
        Assert.Contains("ApplySpecificationForCount", result.GeneratedSources["RynorArch.CrudInfrastructure.g.cs"]);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_stable_specification_output_snapshot()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(Pattern = ArchitecturePattern.Repository, UseSpecification = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; init; } = string.Empty;
            }
            """);

        var generatedSource = Normalize(result.GeneratedSources["Trip.Specification.g.cs"]);

        Assert.Contains("// <auto-generated/>", generatedSource);
        Assert.Contains("using System;", generatedSource);
        Assert.Contains("using System.Collections.Generic;", generatedSource);
        Assert.Contains("using System.Linq.Expressions;", generatedSource);
        Assert.Contains("using RynorArch.Abstractions.Interfaces;", generatedSource);
        Assert.Contains("using Demo.Domain;", generatedSource);
        Assert.Contains("namespace Demo.Domain.Specifications;", generatedSource);
        Assert.Contains("public sealed class TripSpecification : ISpecification<Trip>", generatedSource);
        Assert.Contains("public string? Destination { get; init; }", generatedSource);
        Assert.Contains("Expression<Func<Trip, bool>> filter = x => x.Destination.Contains(Destination!);", generatedSource);
        Assert.Contains("public IReadOnlyList<Expression<Func<Trip, object>>> Includes { get; init; } = Array.Empty<Expression<Func<Trip, object>>>();", generatedSource);
        Assert.Contains("return Expression.Lambda<Func<Trip, bool>>(combined, parameter);", generatedSource);
    }

    [Fact]
    public void Emits_unit_of_work_once_for_multiple_entities()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.FullStack,
                UseSpecification = true,
                UseUnitOfWork = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; set; } = string.Empty;
            }

            [Entity]
            public partial class Hotel : EntityBase
            {
                [QueryFilter]
                public string Name { get; set; } = string.Empty;
            }
            """,
            """
            using Microsoft.EntityFrameworkCore;
            using Demo.Domain;

            namespace Demo.Domain.Cqrs;

            public sealed class AppDbContext : DbContext
            {
                public DbSet<Trip> Trips => Set<Trip>();
                public DbSet<Hotel> Hotels => Set<Hotel>();
            }
            """);

        Assert.Equal(1, result.GeneratedHintNames.Count(name => name == "IUnitOfWork.g.cs"));
        Assert.Contains("queryable = queryable.Where(x => x.Destination.Contains(query.Destination!));", result.GeneratedSources["Trip.Cqrs.g.cs"], StringComparison.Ordinal);
        Assert.Contains("Expression<Func<Trip, bool>> filter = x => x.Destination.Contains(Destination!);", result.GeneratedSources["Trip.Specification.g.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_fullstack_feature_set_for_aggregate_roots()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.FullStack,
                UseSpecification = true,
                UseUnitOfWork = true,
                EnableValidation = true,
                GenerateDtos = true,
                GenerateEfConfigurations = true,
                GenerateCachingDecorators = true,
                GeneratePagination = true)]

            namespace Demo.Domain;

            [Entity]
            [AggregateRoot]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; set; } = string.Empty;
            }
            """,
            """
            using Microsoft.EntityFrameworkCore;
            using Demo.Domain;

            namespace Demo.Domain.Cqrs;

            public sealed class AppDbContext : DbContext
            {
                public DbSet<Trip> Trips => Set<Trip>();
            }
            """);

        Assert.Contains("Trip.Cqrs.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Repository.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.CrudInfrastructure.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.GenerationReport.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Specification.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Validation.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripDto.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripConfiguration.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("GetTripByIdQueryCacheBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripPaginationExtensions.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.DomainEvents.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("IUnitOfWork.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("// rynor-artifact: CQRS", result.GeneratedSources["Trip.Cqrs.g.cs"]);
        Assert.Contains("// rynor-assumptions: uses configured DbContext type for handlers", result.GeneratedSources["Trip.Cqrs.g.cs"]);
        Assert.Contains("public static readonly string[] Artifacts = new[]", result.GeneratedSources["RynorArch.GenerationReport.g.cs"]);
        Assert.Equal(1, result.GeneratedHintNames.Count(name => name == "IUnitOfWork.g.cs"));
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_cqrs_save_behavior_for_per_request_transaction_mode()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;
            using Microsoft.EntityFrameworkCore;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.Cqrs,
                CqrsSaveMode = CqrsSaveMode.PerRequestTransaction,
                DbContextType = typeof(Demo.Domain.AppDbContext))]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                public string Destination { get; set; } = string.Empty;
            }

            public sealed class AppDbContext : DbContext
            {
                public DbSet<Trip> Trips => Set<Trip>();
            }
            """);

        Assert.Contains("RynorArch.CqrsSaveBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("IRynorArchWriteCommand", result.GeneratedSources["RynorArch.CqrsSaveBehavior.g.cs"]);
        Assert.Contains("CreateTripCommand : IRequest<Guid>, IRynorArchWriteCommand", result.GeneratedSources["Trip.Cqrs.g.cs"]);
        Assert.Contains("await RynorArchCrudRuntime.AddAsync(_db, entity, cancellationToken);", result.GeneratedSources["Trip.Cqrs.g.cs"]);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    private static string Normalize(string value)
        => value.Replace("\r\n", "\n").Trim();
}
