using Xunit;

namespace RynorArch.Generator.Tests;

public sealed class GeneratorOutputTests
{
    [Fact]
    public void Generates_repository_and_specification_outputs_without_compilation_errors()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;
            using Microsoft.EntityFrameworkCore;

            [assembly: Architecture(Pattern = ArchitecturePattern.Repository, UseSpecification = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; init; } = string.Empty;
            }
            """);

        Assert.Contains("Trip.Repository.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Specification.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.CrudInfrastructure.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.GenerationReport.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("public interface ITripRepository : ICrudRepository<Trip>;", result.GeneratedSources["Trip.Repository.g.cs"]);
        Assert.Contains("public sealed partial class TripRepository : CrudRepository<Trip>, ITripRepository", result.GeneratedSources["Trip.Repository.g.cs"]);
        Assert.Contains("private static class EntityTraits<TEntity> where TEntity : class", result.GeneratedSources["RynorArch.CrudInfrastructure.g.cs"]);
        Assert.Contains("// rynor-artifact: Global.GenerationReport", result.GeneratedSources["RynorArch.GenerationReport.g.cs"]);
        Assert.Contains("ApplySpecificationForList", result.GeneratedSources["RynorArch.CrudInfrastructure.g.cs"]);
        Assert.Contains("ApplySpecificationForCount", result.GeneratedSources["RynorArch.CrudInfrastructure.g.cs"]);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_stable_specification_output_snapshot()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(Pattern = ArchitecturePattern.Repository, UseSpecification = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; init; } = string.Empty;
            }
            """);

        var generatedSource = Normalize(result.GeneratedSources["Trip.Specification.g.cs"]);

        Assert.Contains("// <auto-generated/>", generatedSource);
        Assert.Contains("using System;", generatedSource);
        Assert.Contains("using System.Collections.Generic;", generatedSource);
        Assert.Contains("using System.Linq.Expressions;", generatedSource);
        Assert.Contains("using RynorArch.Abstractions.Interfaces;", generatedSource);
        Assert.Contains("using Demo.Domain;", generatedSource);
        Assert.Contains("namespace Demo.Domain.Specifications;", generatedSource);
        Assert.Contains("public sealed class TripSpecification : ISpecification<Trip>", generatedSource);
        Assert.Contains("public string? Destination { get; init; }", generatedSource);
        Assert.Contains("Expression<Func<Trip, bool>> filter = x => x.Destination.Contains(Destination!);", generatedSource);
        Assert.Contains("public IReadOnlyList<Expression<Func<Trip, object>>> Includes { get; init; } = Array.Empty<Expression<Func<Trip, object>>>();", generatedSource);
        Assert.Contains("return Expression.Lambda<Func<Trip, bool>>(combined, parameter);", generatedSource);
    }

    [Fact]
    public void Emits_unit_of_work_once_for_multiple_entities()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.FullStack,
                UseSpecification = true,
                UseUnitOfWork = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; set; } = string.Empty;
            }

            [Entity]
            public partial class Hotel : EntityBase
            {
                [QueryFilter]
                public string Name { get; set; } = string.Empty;
            }
            """,
            """
            using Microsoft.EntityFrameworkCore;
            using Demo.Domain;

            namespace Demo.Domain.Cqrs;

            public sealed class AppDbContext : DbContext
            {
                public DbSet<Trip> Trips => Set<Trip>();
                public DbSet<Hotel> Hotels => Set<Hotel>();
            }
            """);

        Assert.Equal(1, result.GeneratedHintNames.Count(name => name == "IUnitOfWork.g.cs"));
        Assert.Contains("queryable = queryable.Where(x => x.Destination.Contains(query.Destination!));", result.GeneratedSources["Trip.Cqrs.g.cs"], StringComparison.Ordinal);
        Assert.Contains("Expression<Func<Trip, bool>> filter = x => x.Destination.Contains(Destination!);", result.GeneratedSources["Trip.Specification.g.cs"], StringComparison.Ordinal);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_unit_of_work_adapter_and_generic_di_overload_for_repository_profile()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(Profile = ArchitectureProfile.RepositoryQuickStart)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; set; } = string.Empty;
            }
            """);

        Assert.Contains("RynorArchServiceCollectionExtensions.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("public static IServiceCollection AddRynorArchDependencies<TDbContext>(this IServiceCollection services, bool registerMediatR = true)", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"]);
        Assert.Contains("services.AddScoped<IUnitOfWork>(sp => new RynorArchGeneratedUnitOfWork<TDbContext>(sp.GetRequiredService<TDbContext>()));", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"]);
        Assert.Contains("public sealed class RynorArchGeneratedUnitOfWork<TDbContext> : IUnitOfWork where TDbContext : DbContext", result.GeneratedSources["RynorArch.CrudInfrastructure.g.cs"]);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_fullstack_feature_set_for_aggregate_roots()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.FullStack,
                UseSpecification = true,
                UseUnitOfWork = true,
                EnableValidation = true,
                GenerateDtos = true,
                GenerateEfConfigurations = true,
                GenerateCachingDecorators = true,
                GeneratePagination = true)]

            namespace Demo.Domain;

            [Entity]
            [AggregateRoot]
            public partial class Trip : EntityBase
            {
                [QueryFilter]
                public string Destination { get; set; } = string.Empty;
            }
            """,
            """
            using Microsoft.EntityFrameworkCore;
            using Demo.Domain;

            namespace Demo.Domain.Cqrs;

            public sealed class AppDbContext : DbContext
            {
                public DbSet<Trip> Trips => Set<Trip>();
            }
            """);

        Assert.Contains("Trip.Cqrs.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Repository.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.CrudInfrastructure.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.GenerationReport.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Specification.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.Validation.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripDto.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripConfiguration.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("GetTripByIdQueryCacheBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("TripPaginationExtensions.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("Trip.DomainEvents.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("IUnitOfWork.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("RynorArch.ValidationBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("// rynor-artifact: CQRS", result.GeneratedSources["Trip.Cqrs.g.cs"]);
        Assert.Contains("// rynor-assumptions: uses configured DbContext type for handlers", result.GeneratedSources["Trip.Cqrs.g.cs"]);
        Assert.Contains("public static readonly string[] Artifacts = new[]", result.GeneratedSources["RynorArch.GenerationReport.g.cs"]);
        Assert.Equal(1, result.GeneratedHintNames.Count(name => name == "IUnitOfWork.g.cs"));
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_cqrs_save_behavior_for_per_request_transaction_mode()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;
            using Microsoft.EntityFrameworkCore;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.Cqrs,
                CqrsSaveMode = CqrsSaveMode.PerRequestTransaction,
                DbContextType = typeof(Demo.Domain.AppDbContext))]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                public string Destination { get; set; } = string.Empty;
            }

            public sealed class AppDbContext : DbContext
            {
                public DbSet<Trip> Trips => Set<Trip>();
            }
            """);

        Assert.Contains("RynorArch.CqrsSaveBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("IRynorArchWriteCommand", result.GeneratedSources["RynorArch.CqrsSaveBehavior.g.cs"]);
        Assert.Contains("CreateTripCommand : IRequest<Guid>, IRynorArchWriteCommand", result.GeneratedSources["Trip.Cqrs.g.cs"]);
        Assert.Contains("await RynorArchCrudRuntime.AddAsync(_db, entity, cancellationToken);", result.GeneratedSources["Trip.Cqrs.g.cs"]);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Applies_cqrs_quickstart_profile_and_emits_auto_di_wiring()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;
            using Microsoft.EntityFrameworkCore;

            [assembly: Architecture(
                Profile = ArchitectureProfile.CqrsQuickStart,
                GenerateCachingDecorators = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                public string Destination { get; set; } = string.Empty;
            }

            public sealed class AppDbContext : DbContext
            {
                public DbSet<Trip> Trips => Set<Trip>();
            }
            """);

        Assert.Contains("RynorArchServiceCollectionExtensions.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("public static IServiceCollection AddRynorArchDependencies(this IServiceCollection services, bool registerMediatR = true)", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"]);
        Assert.Contains("services.AddScoped<IRequestHandler<CreateTripCommand, Guid>, CreateTripHandler>();", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"]);
        Assert.Contains("services.AddScoped<IValidator<CreateTripCommand>, CreateTripValidator>();", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"]);
        Assert.Contains("services.AddScoped(typeof(IPipelineBehavior<,>), typeof(RynorArchValidationBehavior<,>));", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"]);
        Assert.Contains("RynorArch.ValidationBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("services.AddScoped<IPipelineBehavior<GetTripByIdQuery, Trip?>, GetTripByIdQueryCacheBehavior>();", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"]);
        Assert.DoesNotContain(result.Diagnostics, diagnostic => diagnostic.Severity == Microsoft.CodeAnalysis.DiagnosticSeverity.Error);
    }

    [Fact]
    public void Generates_endpoint_extensions_with_correct_write_semantics()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.Cqrs,
                GenerateEndpoints = true,
                EnableExperimentalEndpoints = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                public string Destination { get; set; } = string.Empty;
            }
            """);

        Assert.Contains("RynorArchEndpointExtensions.g.cs", result.GeneratedSources.Keys);
        var endpointSource = result.GeneratedSources["RynorArchEndpointExtensions.g.cs"];

        Assert.Contains("return Results.Created($\"/api/trips/{result}\", new { id = result });", endpointSource);
        Assert.Contains("var success = await mediator.Send(command);", endpointSource);
        Assert.Contains("var success = await mediator.Send(new DeleteTripCommand(id));", endpointSource);
        Assert.Contains("return success ? Results.NoContent() : Results.NotFound();", endpointSource);
        Assert.DoesNotContain("await mediator.Send(command);\r\n            return Results.NoContent();", endpointSource, StringComparison.Ordinal);
        Assert.DoesNotContain("await mediator.Send(new DeleteTripCommand(id));\r\n            return Results.NoContent();", endpointSource, StringComparison.Ordinal);
    }

    [Fact]
    public void Generates_validation_pipeline_behavior_when_validation_enabled()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.Cqrs,
                EnableValidation = true,
                GenerateDependencyInjection = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                [Required]
                public string Destination { get; set; } = string.Empty;
            }
            """);

        Assert.Contains("RynorArch.ValidationBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.Contains("public sealed class RynorArchValidationBehavior<TRequest, TResponse> : IPipelineBehavior<TRequest, TResponse>", result.GeneratedSources["RynorArch.ValidationBehavior.g.cs"]);
        Assert.Contains("services.AddScoped(typeof(IPipelineBehavior<,>), typeof(RynorArchValidationBehavior<,>));", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"]);
    }

    [Fact]
    public void Does_not_generate_validation_pipeline_behavior_when_validation_is_disabled()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.Cqrs,
                EnableValidation = false,
                GenerateDependencyInjection = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                public string Destination { get; set; } = string.Empty;
            }
            """);

        Assert.DoesNotContain("RynorArch.ValidationBehavior.g.cs", result.GeneratedSources.Keys);
        Assert.DoesNotContain("RynorArchValidationBehavior<,>", result.GeneratedSources["RynorArchServiceCollectionExtensions.g.cs"], StringComparison.Ordinal);
    }

    [Fact]
    public void Raises_domain_events_for_aggregate_root_write_handlers()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(Pattern = ArchitecturePattern.Cqrs)]

            namespace Demo.Domain;

            [Entity]
            [AggregateRoot]
            public partial class Trip : EntityBase
            {
                public string Destination { get; set; } = string.Empty;
            }
            """);

        var cqrsSource = result.GeneratedSources["Trip.Cqrs.g.cs"];
        Assert.Contains("using Demo.Domain.DomainEvents;", cqrsSource);
        Assert.Contains("entity.RaiseDomainEvent(new TripCreatedEvent(entity.Id));", cqrsSource);
        Assert.Contains("entity.RaiseDomainEvent(new TripUpdatedEvent(entity.Id));", cqrsSource);
        Assert.Contains("entity.RaiseDomainEvent(new TripDeletedEvent(entity.Id));", cqrsSource);
    }

    [Fact]
    public void Does_not_raise_domain_events_for_non_aggregate_write_handlers()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(Pattern = ArchitecturePattern.Cqrs)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                public string Destination { get; set; } = string.Empty;
            }
            """);

        var cqrsSource = result.GeneratedSources["Trip.Cqrs.g.cs"];
        Assert.DoesNotContain("using Demo.Domain.DomainEvents;", cqrsSource, StringComparison.Ordinal);
        Assert.DoesNotContain("RaiseDomainEvent(", cqrsSource, StringComparison.Ordinal);
    }

    [Fact]
    public void Generates_ef_configuration_for_global_system_string_properties()
    {
        var result = GeneratorTestHarness.Run("""
            using RynorArch.Abstractions.Attributes;
            using RynorArch.Abstractions.Base;
            using RynorArch.Abstractions.Enums;

            [assembly: Architecture(
                Pattern = ArchitecturePattern.Repository,
                GenerateEfConfigurations = true)]

            namespace Demo.Domain;

            [Entity]
            public partial class Trip : EntityBase
            {
                public global::System.String Title { get; set; } = string.Empty;
                public global::System.String? Subtitle { get; set; }
            }
            """);

        Assert.Contains("TripConfiguration.g.cs", result.GeneratedSources.Keys);
        var efSource = result.GeneratedSources["TripConfiguration.g.cs"];
        Assert.Contains("builder.Property(x => x.Title)", efSource);
        Assert.Contains(".IsRequired();", efSource);
        Assert.Contains("builder.Property(x => x.Subtitle)", efSource);
        Assert.Contains(".IsRequired(false);", efSource);
    }

    private static string Normalize(string value)
        => value.Replace("\r\n", "\n").Trim();
}
