using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RynorArch.Generator.Models;

namespace RynorArch.Generator.Emitters;

internal static class CachingEmitter
{
    public static void Emit(SourceProductionContext context, EntityModel entity)
    {
        var sb = new StringBuilder();
        
        string ns = string.IsNullOrEmpty(entity.Namespace) ? "RynorArch.Generated" : $"{entity.Namespace}.Cqrs";
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using MediatR;");
        sb.AppendLine("using Microsoft.Extensions.Caching.Distributed;");
        sb.AppendLine("using System.Text.Json;");
        sb.AppendLine("using System.Threading;");
        sb.AppendLine("using System.Threading.Tasks;");
        if (!string.IsNullOrEmpty(entity.Namespace))
        {
            sb.AppendLine($"using {entity.Namespace};");
        }
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public partial class Get{entity.Name}ByIdQueryCacheBehavior : IPipelineBehavior<Get{entity.Name}ByIdQuery, {entity.Name}?>");
        sb.AppendLine("{");
        sb.AppendLine("    private readonly IDistributedCache _cache;");
        sb.AppendLine($"    public Get{entity.Name}ByIdQueryCacheBehavior(IDistributedCache cache) => _cache = cache;");
        sb.AppendLine();
        sb.AppendLine($"    public async Task<{entity.Name}?> Handle(Get{entity.Name}ByIdQuery request, RequestHandlerDelegate<{entity.Name}?> next, CancellationToken cancellationToken)");
        sb.AppendLine("    {");
        sb.AppendLine($"        var cacheKey = \"{entity.Name}_\" + request.Id;");
        sb.AppendLine("        var cachedSpan = await _cache.GetAsync(cacheKey, cancellationToken);");
        sb.AppendLine("        if (cachedSpan != null)");
        sb.AppendLine("        {");
        sb.AppendLine($"            return JsonSerializer.Deserialize<{entity.Name}>(cachedSpan);");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        var response = await next();");
        sb.AppendLine("        if (response != null)");
        sb.AppendLine("        {");
        sb.AppendLine("            var options = new DistributedCacheEntryOptions().SetSlidingExpiration(TimeSpan.FromMinutes(5));");
        sb.AppendLine("            await _cache.SetAsync(cacheKey, JsonSerializer.SerializeToUtf8Bytes(response), options, cancellationToken);");
        sb.AppendLine("        }");
        sb.AppendLine("        return response;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"Get{entity.Name}ByIdQueryCacheBehavior.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
