using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RynorArch.Generator.Models;

namespace RynorArch.Generator.Emitters;

internal static class DependencyInjectionEmitter
{
    public static void Emit(SourceProductionContext context, ImmutableArray<EntityModel> entities, ArchitectureConfig config)
    {
        if (entities.Length == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// rynor-artifact: Global.DependencyInjection");
        sb.AppendLine("#nullable enable");
        if (config.IsCqrs)
        {
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("using MediatR;");
        }
        if (config.IsCqrs && config.EnableValidation)
        {
            sb.AppendLine("using FluentValidation;");
        }
        if (config.IsRepository && config.UseUnitOfWork)
        {
            sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        }
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        
        // Add using statements for all entity namespaces
        var namespaces = new System.Collections.Generic.HashSet<string>();
        foreach (var entity in entities)
        {
            if (!string.IsNullOrEmpty(entity.Namespace))
            {
                namespaces.Add(entity.Namespace!);
            }
        }
        
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
            if (config.IsCqrs)
            {
                sb.AppendLine($"using {ns}.Cqrs;");
            }
            if (config.IsRepository)
            {
                sb.AppendLine($"using {ns}.Repositories;");
            }
            if (config.IsCqrs && config.EnableValidation)
            {
                sb.AppendLine($"using {ns}.Validation;");
            }
        }

        if ((config.IsCqrs && (config.IsPerRequestTransactionSaveMode || config.EnableValidation))
            || (config.IsRepository && config.UseUnitOfWork))
        {
            sb.AppendLine("using RynorArch.Generated.Infrastructure;");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace RynorArch.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static class RynorArchServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddRynorArchDependencies(this IServiceCollection services, bool registerMediatR = true)");
        sb.AppendLine("    {");

        if (config.IsCqrs)
        {
            sb.AppendLine("        if (registerMediatR)");
            sb.AppendLine("        {");
            sb.AppendLine("            services.AddMediatR(cfg => cfg.RegisterServicesFromAssembly(typeof(RynorArchServiceCollectionExtensions).Assembly));");
            sb.AppendLine("        }");
            sb.AppendLine();
        }

        foreach (var entity in entities)
        {
            if (config.IsCqrs)
            {
                sb.AppendLine($"        services.AddScoped<IRequestHandler<Create{entity.Name}Command, Guid>, Create{entity.Name}Handler>();");
                sb.AppendLine($"        services.AddScoped<IRequestHandler<Update{entity.Name}Command, bool>, Update{entity.Name}Handler>();");
                sb.AppendLine($"        services.AddScoped<IRequestHandler<Delete{entity.Name}Command, bool>, Delete{entity.Name}Handler>();");
                sb.AppendLine($"        services.AddScoped<IRequestHandler<Get{entity.Name}ByIdQuery, {entity.Name}?>, Get{entity.Name}ByIdHandler>();");
                sb.AppendLine($"        services.AddScoped<IRequestHandler<Get{entity.Name}ListQuery, IReadOnlyList<{entity.Name}>>, Get{entity.Name}ListHandler>();");
            }

            if (config.IsCqrs && config.EnableValidation)
            {
                sb.AppendLine($"        services.AddScoped<IValidator<Create{entity.Name}Command>, Create{entity.Name}Validator>();");
                sb.AppendLine($"        services.AddScoped<IValidator<Update{entity.Name}Command>, Update{entity.Name}Validator>();");
            }

            if (config.IsRepository)
            {
                sb.AppendLine($"        services.AddScoped<I{entity.Name}Repository, {entity.Name}Repository>();");
            }

            if (config.IsCqrs && config.GenerateCachingDecorators)
            {
                sb.AppendLine($"        services.AddScoped<IGet{entity.Name}ByIdCacheInvalidator, Get{entity.Name}ByIdDistributedCacheInvalidator>();");
                sb.AppendLine($"        services.AddScoped<IPipelineBehavior<Get{entity.Name}ByIdQuery, {entity.Name}?>, Get{entity.Name}ByIdQueryCacheBehavior>();");
            }

            sb.AppendLine();
        }

        if (config.IsCqrs && config.IsPerRequestTransactionSaveMode)
        {
            sb.AppendLine("        services.AddScoped(typeof(IPipelineBehavior<,>), typeof(RynorArchSaveChangesBehavior<,>));");
            sb.AppendLine();
        }

        if (config.IsCqrs && config.EnableValidation)
        {
            sb.AppendLine("        services.AddScoped(typeof(IPipelineBehavior<,>), typeof(RynorArchValidationBehavior<,>));");
            sb.AppendLine();
        }
        
        sb.AppendLine("        return services;");
        sb.AppendLine("    }");

        if (config.IsRepository && config.UseUnitOfWork)
        {
            sb.AppendLine();
            sb.AppendLine("    public static IServiceCollection AddRynorArchDependencies<TDbContext>(this IServiceCollection services, bool registerMediatR = true)");
            sb.AppendLine("        where TDbContext : DbContext");
            sb.AppendLine("    {");
            sb.AppendLine("        AddRynorArchDependencies(services, registerMediatR);");
            sb.AppendLine("        services.AddScoped<IUnitOfWork>(sp => new RynorArchGeneratedUnitOfWork<TDbContext>(sp.GetRequiredService<TDbContext>()));");
            sb.AppendLine("        return services;");
            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        context.AddSource("RynorArchServiceCollectionExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
