using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RynorArch.Generator.Models;

namespace RynorArch.Generator.Emitters;

internal static class DependencyInjectionEmitter
{
    public static void Emit(SourceProductionContext context, ImmutableArray<EntityModel> entities, ArchitectureConfig config)
    {
        if (entities.Length == 0) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        
        // Add using statements for all entity namespaces
        var namespaces = new System.Collections.Generic.HashSet<string>();
        foreach (var entity in entities)
        {
            if (!string.IsNullOrEmpty(entity.Namespace))
            {
                namespaces.Add(entity.Namespace!);
            }
        }
        
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
            if (config.IsRepository)
            {
                sb.AppendLine($"using {ns}.Repositories;");
            }
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace RynorArch.DependencyInjection;");
        sb.AppendLine();
        sb.AppendLine("public static class RynorArchServiceCollectionExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IServiceCollection AddRynorArchDependencies(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var entity in entities)
        {
            if (config.IsRepository)
            {
                sb.AppendLine($"        services.AddScoped<I{entity.Name}Repository, {entity.Name}Repository>();");
            }
        }
        
        // Unit of Work registration is best left to manual user code since AppDbContext needs specific setup
        // if (config.UseUnitOfWork)
        // {
        //     sb.AppendLine("        services.AddScoped<IUnitOfWork, UnitOfWork>();");
        // }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("RynorArchServiceCollectionExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
