using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RynorArch.Generator.Models;

namespace RynorArch.Generator.Emitters;

internal static class DtoEmitter
{
    public static void Emit(SourceProductionContext context, EntityModel entity)
    {
        var sb = new StringBuilder();
        
        string ns = string.IsNullOrEmpty(entity.Namespace) ? "RynorArch.Generated" : $"{entity.Namespace}.Dtos";
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        if (!string.IsNullOrEmpty(entity.Namespace))
        {
            sb.AppendLine($"using {entity.Namespace};");
        }
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        
        // DTO Record
        sb.AppendLine($"public partial record {entity.Name}Dto");
        sb.AppendLine("{");
        sb.AppendLine("    public Guid Id { get; init; }");
        foreach (var prop in entity.Properties)
        {
            string nullableModifier = prop.IsNullable ? "?" : "";
            sb.AppendLine($"    public {prop.TypeName}{nullableModifier} {prop.Name} {{ get; init; }} = default!;");
        }
        sb.AppendLine("}");
        
        sb.AppendLine();
        
        // Mapper Extension
        sb.AppendLine($"public static partial class {entity.Name}MapperFallback");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {entity.Name}Dto ToDto(this {entity.Name} entity)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (entity is null) throw new System.ArgumentNullException(nameof(entity));");
        sb.AppendLine($"        return new {entity.Name}Dto");
        sb.AppendLine("        {");
        sb.AppendLine("            Id = entity.Id,");
        
        foreach (var prop in entity.Properties)
        {
            sb.AppendLine($"            {prop.Name} = entity.{prop.Name},");
        }
        
        sb.AppendLine("        };");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource($"{entity.Name}Dto.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
