using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RynorArch.Generator.Models;

namespace RynorArch.Generator.Emitters;

internal static class EfCoreEmitter
{
    public static void Emit(SourceProductionContext context, EntityModel entity)
    {
        var sb = new StringBuilder();
        
        string ns = string.IsNullOrEmpty(entity.Namespace) ? "RynorArch.Generated" : $"{entity.Namespace}.Infrastructure.Data.Configurations";
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Microsoft.EntityFrameworkCore;");
        sb.AppendLine("using Microsoft.EntityFrameworkCore.Metadata.Builders;");
        if (!string.IsNullOrEmpty(entity.Namespace))
        {
            sb.AppendLine($"using {entity.Namespace};");
        }
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        sb.AppendLine($"public partial class {entity.Name}Configuration : IEntityTypeConfiguration<{entity.Name}>");
        sb.AppendLine("{");
        sb.AppendLine($"    public void Configure(EntityTypeBuilder<{entity.Name}> builder)");
        sb.AppendLine("    {");
        sb.AppendLine("        builder.HasKey(x => x.Id);");
        sb.AppendLine("        ");
        
        foreach (var prop in entity.Properties)
        {
            if (prop.TypeName == "string")
            {
                // Basic sensible defaults, real world would use attributes for MaxLength
                sb.AppendLine($"        builder.Property(x => x.{prop.Name})");
                if (!prop.IsNullable)
                {
                    sb.AppendLine("               .IsRequired();");
                }
                else
                {
                    sb.AppendLine("               .IsRequired(false);");
                }
            }
        }
        
        sb.AppendLine("        ConfigurePartial(builder);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine($"    partial void ConfigurePartial(EntityTypeBuilder<{entity.Name}> builder);");
        sb.AppendLine("}");

        context.AddSource($"{entity.Name}Configuration.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
