using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using RynorArch.Generator.Models;

namespace RynorArch.Generator.Emitters;

internal static class EndpointEmitter
{
    public static void Emit(SourceProductionContext context, ImmutableArray<EntityModel> entities, ArchitectureConfig config)
    {
        if (entities.Length == 0 || !config.IsCqrs) return;

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using MediatR;");
        
        var namespaces = new System.Collections.Generic.HashSet<string>();
        foreach (var entity in entities)
        {
            if (!string.IsNullOrEmpty(entity.Namespace))
            {
                namespaces.Add(entity.Namespace!);
                namespaces.Add($"{entity.Namespace}.Cqrs");
            }
        }
        
        foreach (var ns in namespaces)
        {
            sb.AppendLine($"using {ns};");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace RynorArch.Endpoints;");
        sb.AppendLine();
        sb.AppendLine("public static class RynorArchEndpointExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapRynorArchEndpoints(this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        foreach (var entity in entities)
        {
            string slug = entity.Name.ToLowerInvariant() + "s";
            
            // Map GET by ID
            sb.AppendLine($"        endpoints.MapGet(\"/api/{slug}/{{id:guid}}\", async (Guid id, [FromServices] IMediator mediator) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            var result = await mediator.Send(new Get{entity.Name}ByIdQuery(id));");
            sb.AppendLine("            return result is not null ? Results.Ok(result) : Results.NotFound();");
            sb.AppendLine($"        }}).WithName(\"Get{entity.Name}ById\")");
            sb.AppendLine($"          .WithTags(\"{entity.Name}\");");
            sb.AppendLine();
            
            // Map POST
            sb.AppendLine($"        endpoints.MapPost(\"/api/{slug}\", async ([FromBody] Create{entity.Name}Command command, [FromServices] IMediator mediator) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            var result = await mediator.Send(command);");
            sb.AppendLine($"            return Results.Created($\"/api/{slug}/{{result}}\", result);"); // Assuming result is ID
            sb.AppendLine($"        }}).WithName(\"Create{entity.Name}\")");
            sb.AppendLine($"          .WithTags(\"{entity.Name}\");");
            sb.AppendLine();
            
            // Map PUT
            sb.AppendLine($"        endpoints.MapPut(\"/api/{slug}/{{id:guid}}\", async (Guid id, [FromBody] Update{entity.Name}Command command, [FromServices] IMediator mediator) =>");
            sb.AppendLine("        {");
            sb.AppendLine("            if (id != command.Id) return Results.BadRequest();");
            sb.AppendLine($"            await mediator.Send(command);");
            sb.AppendLine("            return Results.NoContent();");
            sb.AppendLine($"        }}).WithName(\"Update{entity.Name}\")");
            sb.AppendLine($"          .WithTags(\"{entity.Name}\");");
            sb.AppendLine();
            
            // Map DELETE
            sb.AppendLine($"        endpoints.MapDelete(\"/api/{slug}/{{id:guid}}\", async (Guid id, [FromServices] IMediator mediator) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            await mediator.Send(new Delete{entity.Name}Command(id));");
            sb.AppendLine("            return Results.NoContent();");
            sb.AppendLine($"        }}).WithName(\"Delete{entity.Name}\")");
            sb.AppendLine($"          .WithTags(\"{entity.Name}\");");
            sb.AppendLine();
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        context.AddSource("RynorArchEndpointExtensions.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
