using System.Text;

namespace ZenithArch.Generator.Helpers;

/// <summary>
/// Zero-allocation string builder helper for deterministic source code generation.
/// Uses pooled StringBuilder and provides indentation management.
/// </summary>
internal sealed class SourceWriter
{
    private readonly StringBuilder _sb;
    private int _indent;
    private bool _needsIndent = true;

    public SourceWriter(int capacity = 2048)
    {
        _sb = new StringBuilder(capacity);
    }

    public SourceWriter AppendLine()
    {
        _sb.AppendLine();
        _needsIndent = true;
        return this;
    }

    public SourceWriter AppendLine(string value)
    {
        WriteIndent();
        _sb.AppendLine(value);
        _needsIndent = true;
        return this;
    }

    public SourceWriter Append(string value)
    {
        WriteIndent();
        _sb.Append(value);
        return this;
    }

    public SourceWriter OpenBrace()
    {
        AppendLine("{");
        _indent++;
        return this;
    }

    public SourceWriter CloseBrace(bool semicolon = false)
    {
        _indent--;
        AppendLine(semicolon ? "};" : "}");
        return this;
    }

    public SourceWriter IncreaseIndent()
    {
        _indent++;
        return this;
    }

    public SourceWriter DecreaseIndent()
    {
        if (_indent > 0) _indent--;
        return this;
    }

    public SourceWriter AppendFileHeader()
    {
        AppendLine("// <auto-generated/>");
        AppendLine("// Generated by ZenithArch Source Generator");
        AppendLine("// Do not edit this file manually.");
        AppendLine();
        AppendLine("#nullable enable");
        AppendLine();
        return this;
    }

    public SourceWriter AppendFileHeader(
        string artifactKind,
        string? entityName = null,
        string? assumptions = null)
    {
        AppendLine("// <auto-generated/>");
        AppendLine("// Generated by ZenithArch Source Generator");
        AppendLine("// Do not edit this file manually.");
        AppendLine($"// rynor-artifact: {artifactKind}");
        if (!string.IsNullOrWhiteSpace(entityName))
        {
            AppendLine($"// rynor-entity: {entityName}");
        }

        if (!string.IsNullOrWhiteSpace(assumptions))
        {
            AppendLine($"// rynor-assumptions: {assumptions}");
        }

        AppendLine();
        AppendLine("#nullable enable");
        AppendLine();
        return this;
    }

    private void WriteIndent()
    {
        if (!_needsIndent) return;

        for (int i = 0; i < _indent; i++)
        {
            _sb.Append("    ");
        }

        _needsIndent = false;
    }

    public override string ToString() => _sb.ToString();

    public int Length => _sb.Length;
}
