using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using ZenithArch.Generator.Helpers;
using ZenithArch.Generator.Models;

namespace ZenithArch.Generator.Emitters;

internal static class EndpointEmitter
{
    private const int RequireAuthorizationHardeningMode = 1;

    public static void Emit(SourceProductionContext context, ImmutableArray<EntityModel> entities, ArchitectureConfig config)
    {
        if (entities.Length == 0 || !config.IsCqrs) return;

        var sortedEntities = EntityOrderingHelpers.SortByNamespaceThenName(entities);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// rynor-artifact: Global.Endpoints");
        sb.AppendLine("// rynor-assumptions: CQRS handlers and IMediator are available");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using System;");
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using Microsoft.AspNetCore.Http;");
        sb.AppendLine("using Microsoft.AspNetCore.Mvc;");
        sb.AppendLine("using MediatR;");
        
        var namespaces = new System.Collections.Generic.HashSet<string>();
        for (int i = 0; i < sortedEntities.Length; i++)
        {
            var entity = sortedEntities[i];
            if (!string.IsNullOrEmpty(entity.Namespace))
            {
                namespaces.Add(entity.Namespace!);
                namespaces.Add($"{entity.Namespace}.Cqrs");
            }
        }

        var sortedNamespaces = EntityOrderingHelpers.SortNamespaces(namespaces);
        for (int i = 0; i < sortedNamespaces.Count; i++)
        {
            var ns = sortedNamespaces[i];
            sb.AppendLine($"using {ns};");
        }
        
        sb.AppendLine();
        sb.AppendLine("namespace ZenithArch.Endpoints;");
        sb.AppendLine();
        sb.AppendLine("public static class ZenithArchEndpointExtensions");
        sb.AppendLine("{");
        sb.AppendLine("    public static IEndpointRouteBuilder MapZenithArchEndpoints(this IEndpointRouteBuilder endpoints)");
        sb.AppendLine("    {");

        bool requiresAuthorization = config.EndpointHardeningMode >= RequireAuthorizationHardeningMode;

        for (int i = 0; i < sortedEntities.Length; i++)
        {
            var entity = sortedEntities[i];
            string slug = entity.Name.ToLowerInvariant() + "s";
            
            // Map GET by ID
            sb.AppendLine($"        endpoints.MapGet(\"/api/{slug}/{{id:guid}}\", async (Guid id, [FromServices] IMediator mediator) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            var result = await mediator.Send(new Get{entity.Name}ByIdQuery(id));");
            if (requiresAuthorization)
            {
                sb.AppendLine("            return result is not null ? Results.Ok(result) : Results.NotFound(new ProblemDetails { Title = \"Not Found\", Detail = \"Requested resource was not found.\", Status = StatusCodes.Status404NotFound });");
            }
            else
            {
                sb.AppendLine("            return result is not null ? Results.Ok(result) : Results.NotFound();");
            }
            sb.AppendLine($"        }}).WithName(\"Get{entity.Name}ById\")");
            if (requiresAuthorization)
            {
                sb.AppendLine("          .RequireAuthorization()");
            }
            sb.AppendLine($"          .WithTags(\"{entity.Name}\");");
            sb.AppendLine();
            
            // Map POST
            sb.AppendLine($"        endpoints.MapPost(\"/api/{slug}\", async ([FromBody] Create{entity.Name}Command command, [FromServices] IMediator mediator) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            var result = await mediator.Send(command);");
            sb.AppendLine($"            return Results.Created($\"/api/{slug}/{{result}}\", new {{ id = result }});");
            sb.AppendLine($"        }}).WithName(\"Create{entity.Name}\")");
            if (requiresAuthorization)
            {
                sb.AppendLine("          .RequireAuthorization()");
            }
            sb.AppendLine($"          .WithTags(\"{entity.Name}\");");
            sb.AppendLine();
            
            // Map PUT
            sb.AppendLine($"        endpoints.MapPut(\"/api/{slug}/{{id:guid}}\", async (Guid id, [FromBody] Update{entity.Name}Command command, [FromServices] IMediator mediator) =>");
            sb.AppendLine("        {");
            if (requiresAuthorization)
            {
                sb.AppendLine("            if (id != command.Id) return Results.BadRequest(new ProblemDetails { Title = \"Bad Request\", Detail = \"Route id must match payload id.\", Status = StatusCodes.Status400BadRequest });");
            }
            else
            {
                sb.AppendLine("            if (id != command.Id) return Results.BadRequest();");
            }
            sb.AppendLine($"            var success = await mediator.Send(command);");
            if (requiresAuthorization)
            {
                sb.AppendLine("            return success ? Results.NoContent() : Results.NotFound(new ProblemDetails { Title = \"Not Found\", Detail = \"Requested resource was not found.\", Status = StatusCodes.Status404NotFound });");
            }
            else
            {
                sb.AppendLine("            return success ? Results.NoContent() : Results.NotFound();");
            }
            sb.AppendLine($"        }}).WithName(\"Update{entity.Name}\")");
            if (requiresAuthorization)
            {
                sb.AppendLine("          .RequireAuthorization()");
            }
            sb.AppendLine($"          .WithTags(\"{entity.Name}\");");
            sb.AppendLine();
            
            // Map DELETE
            sb.AppendLine($"        endpoints.MapDelete(\"/api/{slug}/{{id:guid}}\", async (Guid id, [FromServices] IMediator mediator) =>");
            sb.AppendLine("        {");
            sb.AppendLine($"            var success = await mediator.Send(new Delete{entity.Name}Command(id));");
            if (requiresAuthorization)
            {
                sb.AppendLine("            return success ? Results.NoContent() : Results.NotFound(new ProblemDetails { Title = \"Not Found\", Detail = \"Requested resource was not found.\", Status = StatusCodes.Status404NotFound });");
            }
            else
            {
                sb.AppendLine("            return success ? Results.NoContent() : Results.NotFound();");
            }
            sb.AppendLine($"        }}).WithName(\"Delete{entity.Name}\")");
            if (requiresAuthorization)
            {
                sb.AppendLine("          .RequireAuthorization()");
            }
            sb.AppendLine($"          .WithTags(\"{entity.Name}\");");
            sb.AppendLine();
        }

        sb.AppendLine("        return endpoints;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        SourceEmissionHelpers.AddSource(context, "ZenithArchEndpointExtensions.g.cs", sb);
    }
}
