using System.Text;
using Microsoft.CodeAnalysis;
using ZenithArch.Generator.Helpers;
using ZenithArch.Generator.Models;

namespace ZenithArch.Generator.Emitters;

internal static class PaginationEmitter
{
    public static void Emit(SourceProductionContext context, EntityModel entity)
    {
        var sb = new StringBuilder();

        string ns = NamespaceHelpers.Compose(entity.Namespace, "Extensions");
        
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// rynor-artifact: Pagination");
        sb.AppendLine($"// rynor-entity: {entity.Name}");
        sb.AppendLine("#nullable enable");
        if (!string.IsNullOrEmpty(entity.Namespace))
        {
            sb.AppendLine($"using {entity.Namespace};");
        }
        sb.AppendLine();
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        
        // PagedResult wrapper
        sb.AppendLine($"public record Paged{entity.Name}Result(System.Collections.Generic.IEnumerable<{entity.Name}> Items, int TotalCount, int PageIndex, int PageSize);");
        sb.AppendLine();
        
        sb.AppendLine($"public static partial class {entity.Name}PaginationExtensions");
        sb.AppendLine("{");
        sb.AppendLine($"    public static Paged{entity.Name}Result ToPagedResult(this System.Linq.IQueryable<{entity.Name}> query, int pageIndex, int pageSize)");
        sb.AppendLine("    {");
        sb.AppendLine("        int totalCount = System.Linq.Queryable.Count(query);");
        sb.AppendLine("        var items = System.Linq.Queryable.Take(System.Linq.Queryable.Skip(query, pageIndex * pageSize), pageSize);");
        sb.AppendLine($"        return new Paged{entity.Name}Result(items, totalCount, pageIndex, pageSize);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        SourceEmissionHelpers.AddSource(context, $"{entity.Name}PaginationExtensions.g.cs", sb);
    }
}
