name: release

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Publish packages
        if: ${{ env.NUGET_API_KEY != '' }}
        run: ./publish.ps1 -Push -ApiKey "${{ env.NUGET_API_KEY }}"
        shell: pwsh
